# Generated by Django 2.2.2 on 2019-06-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('viz', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
