# Generated by Django 2.2.2 on 2019-06-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0003_auto_20190627_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('T', 'T')], default='M', max_length=1),
        ),
    ]
