# Generated by Django 2.2.2 on 2019-06-28 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0005_auto_20190628_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumid',
            field=models.UUIDField(default=uuid.UUID('a83a8a62-4de1-43cf-9740-53ea9c26d965'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photo_folder'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photoid',
            field=models.UUIDField(default=uuid.UUID('7c31a721-2689-46d8-8e3f-685869bf8819'), primary_key=True, serialize=False, unique=True),
        ),
    ]
