# Generated by Django 2.2.2 on 2019-06-29 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0008_auto_20190629_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumid',
            field=models.UUIDField(default=uuid.UUID('e927d51e-c6b6-45eb-a8b4-a59f5c8feaa4'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photoid',
            field=models.UUIDField(default=uuid.UUID('e2c1dd65-121c-4bab-bbbb-ea1bbe651132'), primary_key=True, serialize=False, unique=True),
        ),
    ]
