# Generated by Django 2.2.2 on 2019-07-13 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0013_auto_20190711_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='share',
            field=models.CharField(choices=[('P', 'Private'), ('U', 'Only by URL'), ('B', 'Public')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='album',
            name='albumid',
            field=models.UUIDField(default=uuid.UUID('82d5a32e-f0ab-4c20-9f46-a5be0610aaf3'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photoid',
            field=models.UUIDField(default=uuid.UUID('e40b913c-c322-4c2d-918d-cdc2909f2750'), primary_key=True, serialize=False, unique=True),
        ),
    ]
