# Generated by Django 2.2.2 on 2019-07-13 06:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0015_auto_20190713_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='share',
            field=models.CharField(choices=[('P', 'Private'), ('U', 'Only by URL'), ('B', 'Public')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='album',
            name='albumid',
            field=models.UUIDField(default=uuid.UUID('37f4358b-169d-4981-a2d2-3a6d6c86adf0'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='share',
            field=models.CharField(choices=[('P', 'Private'), ('U', 'Only by URL'), ('B', 'Public')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photoid',
            field=models.UUIDField(default=uuid.UUID('62e97b82-d315-4af1-9795-4eb9eb3af9cf'), primary_key=True, serialize=False, unique=True),
        ),
    ]
